name: docker-build

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push cloudflare
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.cloudflare
          push: true
          tags: sorashu/caddy:cloudflare
      -
        name: Build and push trojan
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.trojan
          push: true
          tags: sorashu/caddy:trojan

